[supervisord]
nodaemon=true
user=root

[program:node-api]
# Command to start your API
command=node /app/api/app.js
directory=/app/api
autostart=true
autorestart=true
# Redirect logs to docker output
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
