#!/bin/sh

# Check for the lock file
if [ -f ".changelog.lock" ]; then
    rm .changelog.lock
    exit 0
fi

# Create the lock file
touch .changelog.lock

# Run changelog
exec < /dev/tty
npm run changelog

# Add CHANGELOG.md if it was modified
if git diff --name-only | grep -q "^CHANGELOG.md$"; then
    git add CHANGELOG.md
fi

# Clean up lock file
rm .changelog.lock
